### ISSUE TITLE
Feature/order/#36 delivery fee swagger - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#177]
In GitLab by @SubinHeo on Oct 8, 2024, 14:58

_Merges feature/order/#36-deliveryFee_swagger -> test-develop_

- 총 주문 금액에 따른 배송비 설정
- swagger api 어노테이션 추가

**Comment by Engineering-Student-An** [comment]
In GitLab by @SubinHeo on Oct 8, 2024, 14:58

mentioned in commit dc5d9425e6f4c5dde095082fd33e9ae64eeec012
