### ISSUE TITLE
feat: Product 커스텀에러처리 & ApiRespone 추가 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#178]
In GitLab by @hahyun on Oct 8, 2024, 15:11

_Merges feature/product/#35-exception -> test-develop_

- CusomError 코드
- Service 에서 에러 처리
- Controller 에서 @ApiResponse 추가 -> swagger에서 확인 가능

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 8, 2024, 15:11

mentioned in commit bfadfde0eb7e9ad1a43f2d1efe912d87448026b1
