### ISSUE TITLE
refactor: api의 uri 수정 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#179]
In GitLab by @anchangmin on Oct 8, 2024, 20:56

_Merges refactor/cart/#37-refactorURI -> test-develop_

장바구니 api의 uri 수정

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Oct 8, 2024, 20:57

mentioned in commit 40ce593acb3707532cc1aab9991598876a4f8818
