### ISSUE TITLE
feat: MemberResponseDto 에 phone 필드 추가 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#188]
In GitLab by @wlsdud2528 on Oct 9, 2024, 16:31

_Merges feature/member/#44-addPhoneInResponse -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @wlsdud2528 on Oct 9, 2024, 16:31

mentioned in commit e0ffefa634b8503109b0b9fd9c9307f2ea37dcab
