### ISSUE TITLE
refactor: 변경된 exception 패키지 구조로 수정 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#189]
In GitLab by @wlsdud2528 on Oct 9, 2024, 16:36

_Merges feature/member/#43-useCustomException -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @wlsdud2528 on Oct 9, 2024, 16:36

mentioned in commit a7a54fde6b969775ac9dcdcbfaa02d5cd469c5c2
