### ISSUE TITLE
refactor: (오전 코드리뷰) manufacturer 필드 중복 오류 해결 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#201]
In GitLab by @anchangmin on Oct 11, 2024, 11:11

_Merges review-develop -> develop_

refactor: (오전 코드리뷰) manufacturer 필드 중복 오류 해결

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Oct 11, 2024, 11:12

mentioned in commit 6366a40e07b03853db8986aa45db9ea99ab1044a
