### ISSUE TITLE
Feature/product/#71 pagination - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#244]
In GitLab by @hahyun on Oct 17, 2024, 13:06

_Merges feature/product/#71-pagination -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 17, 2024, 13:06

mentioned in commit 784b98605efefb0f86d7de8b9e9ba61ed63d1ebc
