### ISSUE TITLE
feat: SecurityConfig - Product, categories 관련 uri에 permitAll() 추가 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#277]
In GitLab by @hahyun on Oct 22, 2024, 02:23

_Merges feature/product/#98-fixSearchKeyword -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 22, 2024, 02:23

mentioned in commit a36b5ffe6963161c36ce9d008380f6b9911e5c9c
