### ISSUE TITLE
refactor: category 정렬 수정 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#281]
In GitLab by @yooyeonjoo on Oct 22, 2024, 14:41

_Merges feature/category/#109-categoryOrder -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @yooyeonjoo on Oct 22, 2024, 14:41

mentioned in commit ae4e8bf14a2890b5a19fdadeb55967d36112675e
