### ISSUE TITLE
refactor: category, product isdeletedFalse - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#297]
In GitLab by @yooyeonjoo on Oct 24, 2024, 10:54

_Merges feature/category50 -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @yooyeonjoo on Oct 24, 2024, 10:54

mentioned in commit a61db2f9b218ef3a5a72834a0ae9fbc6aa4fdfd3
