### ISSUE TITLE
feat: member SoftDelete + 비활성화된 멤버 제외 조회

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#40]
In GitLab by @wlsdud2528 on Oct 9, 2024, 12:25

**Comment by Engineering-Student-An** [comment]
In GitLab by @wlsdud2528 on Oct 9, 2024, 12:28

mentioned in commit 658c13da365113ce92a20351ed0d340dd13c8d7f

**Comment by Engineering-Student-An** [comment]
In GitLab by @wlsdud2528 on Oct 9, 2024, 12:42

mentioned in commit 26cbf4888100629983fbf19725635af91dc343b8
