### ISSUE TITLE
feat: S3 이미지

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#41]
In GitLab by @hahyun on Oct 9, 2024, 13:01

- Product, category에 s3 이미지 삽입

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 9, 2024, 14:24

mentioned in commit d734b45d024c251873015f9b282a5f7aa345b48c

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 11, 2024, 10:50

mentioned in commit 4322bce9a4d6b7fe1c9b7cbf2cd6fac740b6c250

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 11, 2024, 14:51

mentioned in commit d75b96d00535c9dc1c5db388302baa9020ca183e
