### ISSUE TITLE
feat: exception handler에 유효성 검사 관련 예외 처리 추가

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside#91]
In GitLab by @anchangmin on Oct 18, 2024, 12:56

- MethodArgumentNotValidException.class 관련 예외 처리 메서드 추가

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Oct 18, 2024, 12:58

mentioned in commit aae8d863acf0669a656fb98b8264ec44114c1468
